### ISSUE TITLE
The pie chart in Dashboard should display the proper colour and print the list

### ISSUE THREAD

**Issue by Swapnil73** [priyankapolley30/Iem_Rage_Release0.1#2]
The pie chart in Dashboard should display the proper color and print the generated list

**Comment by priyankapolley30** [comment]
Now the pie chart in dashboard displays the proper color for neutral,positive,negative. For neutral it displays gray color,for negative it displays red and for positive it displays green and now the print option is added.

**Comment by Swapnil73** [comment]
okay
